name: SteveFarkas
favicon: null
layout_spectrum: 0.9743073205463588
typography_spectrum: 0.7199348700232804
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.45984898041933775
  lightness: 0.8363603143952787
  saturation: 0.7423897264525294
  rhythmicContrast: 0.8500934923067689
purpose: []
